### ISSUE TITLE
multiple time prediction

### ISSUE THREAD

**Issue by kikyou123** [coxlab/prednet#30]
i thick there is something wrong about multiple time prediction,. **you say  Starting at this time step, the prediction from the previous time step will be treated as the actual input**, but in time t-1, you prediction is not the image in time t, but the image in time t-1, so how can you treat it the goundtruth in time t?

**Comment by bill-lotter** [comment]
Maybe it's just semantics, but essentially the model in default mode continuously makes t+1 predictions based off of the frame at t (and all the previous frames). When it's in multi-step mode with T being the last input frame to be used, then when it gets to T+2 prediction, instead of iterating off of the ground truth at T+1, the prediction for T+1 is treated as "ground truth".
