### ISSUE TITLE
Trying to use predenet on different data. 

### ISSUE THREAD

**Issue by Daniel-Orlandi** [coxlab/prednet#33]
Hi,
I'm trying to use predenet on a different dataset of mine. The frames have the same size as the Kitti dataset but the code to pre-process the data still failing. I'm wondering ,  can I  use predenet on different data if the frames have the same size as the Kitti dataset or I need to do some kind of pre-processing on the data before running the code to do the pre-process ?
Thanks in advance.

**Comment by PyPatel** [comment]
If it's error in training, I would say It is due to validation set, It has to have a different address for each video. to get the idea, Please do the following: 
Go to process_kitti.py and print the `sources_list` before `hkl.dump`
It works on all type of data set, just you have to generate Hickle files properly (I have tried on like 12 different data  sets including virtual environment).

**Comment by srinadhu** [comment]
@PyPatel  The dataset I am trying to use is too large (around 150GB) then I can't simply convert it into hickle file all the data, what should I do?
