### ISSUE TITLE
Enquiry about the performance of PredNet in Comma.ai dataset

### ISSUE THREAD

**Issue by cardwing** [coxlab/prednet#37]
Dear lotter,
     I am HOU Yuenan,  a PhD student from the Chinese University of Hong Kong. I am interested in your paper "Deep predictive coding networks for video prediction and unsupervised learning" and I wish to clarify a few points with you. Your help is much appreciated.
     (1) As far as I know, there is no official train/test partitions for the Comma.ai dataset. I wonder how the data is divided in your paper since a random continuous chunk of 11 video clips is chosen as the testing set in your setting. I wish to compare fairly with your approach on the same train/test partitions.
     (2) Do the following two figures depict the performance of PredNet in your selected testing set? It is quite impressive since you use only a small part of training set (25k labeled training samples) and achieve so good results.  
    Looking forward to your reply!
    Regards,
    Yuenan 
![66](https://user-images.githubusercontent.com/23656119/35495334-6ce4027c-04fb-11e8-92d5-e1cfa65b6450.png)
![67](https://user-images.githubusercontent.com/23656119/35495342-73b8a454-04fb-11e8-80ac-1e6d9391a285.png)

**Comment by bill-lotter** [comment]
Hi @cardwing 

Yes I use 5% of each of the 11 clips for validation and testing, chosen randomly as a continuous chunk. Here are the start and end frame numbers for each clip:

For val:
2016-04-21--14-48-08.h5: 9170-10690
2016-01-31--19-19-25.h5: 10280-11260
2016-03-29--10-50-20.h5: 52838-56760
2016-01-30--13-46-00.h5: 49534-52474
2016-02-11--21-32-47.h5: 55854-60114
2016-02-08--14-56-28.h5: 5780-7060
2016-02-02--10-16-58.h5: 31102-33902
2016-01-30--11-24-51.h5: 27650-30270
2016-06-02--21-39-29.h5: 16510-18750
2016-06-08--11-46-01.h5: 7826-8726
2016-05-12--22-20-00.h5: 20062-22642

For test:
2016-04-21--14-48-08.h5: 19316-20842
2016-01-31--19-19-25.h5: 14708-15694
2016-03-29--10-50-20.h5: 40980-44904
2016-01-30--13-46-00.h5: 38162-41112
2016-02-11--21-32-47.h5: 31864-36128
2016-02-08--14-56-28.h5: 8978-10272
2016-02-02--10-16-58.h5: 44486-47294
2016-01-30--11-24-51.h5: 38388-41024
2016-06-02--21-39-29.h5: 32552-34792
2016-06-08--11-46-01.h5: 12136-13044
2016-05-12--22-20-00.h5: 30846-33430

I discard the first 20 frames before and after each chunk and also discard the first and last 2000 frames at the start and end of each clip (the beginning and ends of the clips can be weird). Otherwise, all the remaining segments are available for training. I also downsample all of the clips by a factor of 2 in time (to be at 10Hz) before I do anything, although the frame numbers above are in reference to the pre-downsampled clips.

Let me know if that makes sense and if you have any other questions. And yes, the plots above are made with the splits above.

Best,
Bill

**Comment by cardwing** [comment]
Dear Bill,
    Thanks for your reply. I will test my algorithm in this setting.
Regards,
Yuenan

**Comment by cardwing** [comment]
Dear Bill,
    I have tested my algorithm in your provided setting. It really works. However, I have roughly checked the testing set and have found that the steering angles are mainly near zero. A suggested dividing criterion is to take the first 90 % as training set, 5% as val set and the rest as testing set. Anyway, thanks for your response. I will close this issue.
Regards,
Yuenan

**Comment by cardwing** [comment]
Dear Bill,
I perform a little data cleaning in your divided testing set since there are some video frames where the car is stopping in the garage and they are obviously meaningless in the testing process. After this process, I have a total number of 23642 video frames for testing (Your testing set contains 26131 video frames).
Regards,
Yuenan
